In [1]:
import numpy as np

In [3]:
mylist = [1, 2, 3, 4]

In [4]:
type(mylist)

list

In [6]:
myarr = np.array(mylist)

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
type(my_matrix)

list

In [10]:
np_matrix = np.array(my_matrix)

In [12]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
np.linspace(0, 5, num=21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [33]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.random.rand(3, 2, 2)

array([[[0.71534326, 0.92408473],
        [0.09318985, 0.65979351]],

       [[0.20819173, 0.95630081],
        [0.0164741 , 0.0354922 ]],

       [[0.7245381 , 0.25996327],
        [0.69801498, 0.33083407]]])

In [39]:
np.random.randn(3, 2)

array([[-0.7650851 ,  0.55981745],
       [-2.54845964, -0.80902676],
       [-1.64633677, -0.47312544]])

In [42]:
np.random.randint(0, 101, size=(3, 9))

array([[95, 63, 11, 74, 70, 73, 30, 15, 86],
       [89, 87, 28, 88, 91, 94, 39, 82, 65],
       [65, 78, 31, 15, 20, 87, 52, 59,  6]])

In [51]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [88]:
array = np.arange(0, 25)

In [89]:
array.shape

(25,)

In [53]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [85]:
array = array.reshape(5, 5)

In [86]:
array.shape

(5, 5)

In [96]:
array = array.reshape(1, 25)
array.shape, array

((1, 25),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24]]))

In [55]:
ranarr = np.random.randint(0, 101, 10)

In [74]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [75]:
ranarr.max(), ranarr.min()

(99, 2)

In [76]:
ranarr.argmax()

5

In [77]:
ranarr.argmin()

7

In [78]:
ranarr.dtype, ranarr.shape, ranarr.ndim

(dtype('int64'), (10,), 1)

In [81]:
ranarr = ranarr.reshape(2, 5)

In [82]:
ranarr.shape, ranarr.ndim

((2, 5), 2)

In [97]:
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [114]:
arr = np.arange(0, 11)

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr[8]

8

In [117]:
arr[1: 4]

array([1, 2, 3])

In [118]:
arr[: 5]

array([0, 1, 2, 3, 4])

In [119]:
arr[5: ]

array([ 5,  6,  7,  8,  9, 10])

In [120]:
arr[: 5] = arr[: 5] * 100

In [121]:
arr

array([  0, 100, 200, 300, 400,   5,   6,   7,   8,   9,  10])

In [122]:
arr = np.arange(0, 11)

In [125]:
slice_of_arr = arr[0: 5]

In [126]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [128]:
slice_of_arr[:] = 99

In [129]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [130]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [137]:
arr_copy = arr.copy()

In [138]:
arr_copy[:] = 932

In [139]:
arr, arr_copy

(array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10]),
 array([932, 932, 932, 932, 932, 932, 932, 932, 932, 932, 932]))

In [158]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [159]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [160]:
arr_2d.shape

(3, 3)

In [161]:
arr_2d[1]

array([20, 25, 30])

In [162]:
arr_2d[-1]

array([35, 40, 45])

In [173]:
arr_2d_copy = arr_2d[:2, 1:].copy()

In [174]:
arr_2d_copy[:, :] = 39

In [175]:
arr_2d_copy, arr_2d

(array([[39, 39],
        [39, 39]]),
 array([[ 5, 10, 15],
        [20, 25, 30],
        [35, 40, 45]]))

In [176]:
arr = np.arange(1, 11)

In [177]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [179]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [185]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [186]:
dice_rolls

array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6,
       3, 6, 2, 3, 5, 6, 5])

In [191]:
dice_rolls[dice_rolls]

array([2, 1, 1, 5, 1, 1, 1, 1, 1, 5, 5, 1, 5, 1, 2, 5, 1, 5, 5, 5, 1, 1,
       2, 1, 5, 2, 1, 1, 1])

In [192]:
np.count_nonzero(dice_rolls > 2)

19

In [193]:
arr = np.arange(0, 10)
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [194]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [195]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [196]:
arr ** arr

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [197]:
0 ** 0

1

In [198]:
arr / arr

/home/alllowd/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [199]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [200]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [201]:
np.log(arr)

/home/alllowd/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [202]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
arr.sum()

45

In [204]:
np.sum(arr)

45

In [205]:
arr.mean()

4.5

In [206]:
np.mean(arr)

4.5

In [207]:
arr.var()

8.25

In [208]:
np.var(arr)

8.25

In [209]:
arr.std()

2.8722813232690143

In [210]:
np.std(arr)

2.8722813232690143

In [225]:
arr_2d = np.arange(0, 25).reshape(5, 5)

In [226]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [227]:
np.mean(arr_2d, axis=1)

array([ 2.,  7., 12., 17., 22.])

In [229]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])